### ISSUE TITLE
System.Runtime.Caching is not supported on this platform.

### ISSUE THREAD

**Issue by guillermobejarano** [LeximSoluciones/Lexim-MercadoPago-Sdk#11]
Hi all, 
I'm getting an error when I saving and posting Mercadopago's preferences. I believe that System.Runtime.Caching is not supported on .net core 2.1

Error;
An error has occured in the cache structure (REMOVE): System.Runtime.Caching is not supported on this platform.
  at MercadoPago.MPCache.RemoveFromCache(String key)
   at MercadoPago.Resource`1.TryAddToCache(Boolean useCache, String cacheKey, MPAPIResponse response)
   at MercadoPago.Resource`1.Invoke(HttpMethod httpMethod, String path, PayloadType payloadType, JObject payload, String accessToken, Dictionary`2 queryParameters, Boolean useCache, Int32 requestTimeout, Int32 retries)
   at MercadoPago.Resource`1.Send(T resource, HttpMethod httpMethod, String path, Boolean useCache, Int32 requestTimeout, Int32 retries)
   at MercadoPago.Resource`1.Post(String path, Boolean useCache, Int32 requestTimeout, Int32 retries)
   at MercadoPago.Resources.Preference.Save()
   at Nop.Plugin.Payments.MercadoPago.MercadoPagoPaymentProcessor.PostProcessPayment(PostProcessPaymentRequest postProcessPaymentRequest)
   at Nop.Services.Payments.PaymentService.PostProcessPayment(PostProcessPaymentRequest postProcessPaymentRequest) in C:\Repositories\Terere\nopCommerce\src\Libraries\Nop.Services\Payments\PaymentService.cs:line 206
   at Nop.Web.Controllers.CheckoutController.ConfirmOrder() in C:\Repositories\Terere\nopCommerce\src\Presentation\Nop.Web\Controllers\CheckoutController.cs:line 934

**Comment by 15mgm15** [comment]
@guillermobejarano Did you solve this issue?

**Comment by fberasategui** [comment]
Publicada la versión [2.0.4](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/2.0.4), que resuelve el issue de `System.Runtime.Caching`.

**Comment by 15mgm15** [comment]
Gracias!
